apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: ">=8.0.10"
  interval: 10m
  timeout: 20m
  targetNamespace: minio
  values:
    consoleIngress:
      enabled: true
      hosts:
        - minio.localhost
      ingressClassName: nginx
      path: /
    replicas: 2
    existingSecret: minio
    defaultBuckets: "kubeflex"
    resources:
      limits:
      requests:
        cpu: 10m
        memory: 40Mi
    serviceAccount:
      create: true
      name: "minio"