apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: ">=5.4.0"
  interval: 1m0s
  timeout: 20m
  targetNamespace: minio
  values:
    ingress:
      enabled: true
      hosts:
        - minio.localhost
      ingressClassName: nginx
      path: /
    replicas: 2
    auth:
      existingSecret: minio
    defaultBuckets: "kubeflex"
    resources:
      limits:
      requests:
        cpu: 10m
        memory: 40Mi
    serviceAccount:
      create: true
      name: "minio"