apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: ">=17.0.21"
  interval: 1m0s
  timeout: 20m
  targetNamespace: minio
  values:
    global:
      imageRegistry: "bitnamilegacy/minio"
    auth:
      existingSecret: minio
    defaultBuckets: "kubeflex"
    resources:
      limits:
      requests:
        cpu: 10m
        memory: 40Mi
    serviceAccount:
      create: false
      name: "minio"