apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: minio
  namespace: minio
spec:
  encryptedData:
    root-password: AgAerES2+c4J73EA8GNIdhVRs5uXbhqQlpH06UfSS76iVNqvQgRTp4rnk/ks591tnmD281038/q8BMPjRojEacm9JsYsQK47SzQ/ZHidUnF+bRyULs8AAU8yKri07Vddli7W2lJVD28QVfnP60wPwI8xH2NuexDKqaWcZxTB4mdSn8WtyzAGQtnVOgPjw7QKc4IjF9RXtaUq6+dJTHkaoWVlrGIAfMsGD6la/CbNkjj8QcTqRUt3MnUym16RT9hVCuhVwxZNCVUTp4UGKyR5YX5/kVJxIKcvyA1xQdkfU3ig5ZgXyTldLb1YAG+zvjOSJguIv40iFD81M0xHugodUCpxM42qOui205i0aDnNJf8uimY33iFk1cYhOWv3zhiYfVE1d+MuWtLx++LkeqAJHcuHxAlmTMA+QBlsC5ZulHBY+2Sk7GkQStoGhL8eAPB2cjUWHP0vZoJTPPmRSHF8DkU6EqVWMpyMgXpZrnaPOq/0SgG9aqyRaA92UeXH14kk+0L3HFzw3a3YZaGIA+sHz1hiEaeSbaPLPAOmCYzKbspcEjJCFFCWTPVxXRR0eeDkHcv6QjfNlrO+KiC20wxx/iHoKu3erHJukZQX1NZqy38XdShtLFN46NwWFacNMLJteiLWiER1d3oALqYb6AM3I+WR78jr1M50dtZmLoaLOsCahAl47clyb9I/IlVwLYdLFmoGYa57p4hEC22X3pnB9XlipixQ
    root-user: AgCVcJOHihwfiCWDx9EUL/n+RcE5aHPXa24cNXM3ITSYDWubUbo8A2DAw+cvIisw9AHe1mLjPC9XhM2Ko4hVjmoMUbyCliF62OeqmCr7zf7F4EbDoBDFn9EiiKY0m06eYimrHTyP2XfpDE6/XtLpMsq4qUyz4b28kCjx1QddJjgbHWJCUuxnY1Xt8I/SsV2zruki+MXAcDV8ja0/Ozcd9x6zVyZgwc7rgPMsBBCovuIDClT2Ud44ZdENy1UdYL8RGBuLE/tQ9+kDuPruoR8wsnIgpZzHxqASf/rmoW9OS/eoaHtMcD+rDEqWetec7V+PEiboONfKnJu/5JpXLBK2yCFKVi5jDtlSri1zuuX+gFB5xQyA+xPrnf8aClxI1CgphwqZIRo4yLssY8kM2IFiiaG08EPxXmAq1oE9gtaw3VkJ9e6q8qmXoSu9fyOX/6HUqCZJnkYzi0UqV7RrV8aZUyGpaO1G21yG3Kox4InfRu3Z/i+21Ih7ZWjYSQCAuFSbBUkglql+KrPO56UyBPtpi2KCl8KYbrqTv2/3Y+z83bWtdEQhp1LfPEOZbXCT+l+jsHy1rDZI4OXtuzze1dIIwyeMYFxMu3ta0jgmqP0wsgKDjVnSBvo1AuGuY9vAaRuPF8lBaz9zYYwEk8xiVQML+me70Cq1gCRQigrQcQ0bThQSIid8bHeTmjjS9ZX7dFbGHPBaAoYviv0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: minio
      namespace: minio
