apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-mirror-config
  namespace: flux-system
data:
  .terraformrc: |
    provider_installation {
      network_mirror {
        url = "https://terraform-registry-mirror.ru/"
      }
    }
  .tofurc: |
    provider_installation {
      network_mirror {
        url = "https://terraform-registry-mirror.ru/"
      }
    }