apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgC23C/er5dq2gHReTcuru8UNWDVD4L6lGUuAQfy4xFRzX97j0LajtkNqgn+Mz9XCi7uWY+cINQ3UuvOcuj+aWTp86aiYpdkpd0GiyIllghKdWUu093ro3mYw7lzse9I6wrvlDKmNnqmZr8LXexIUU7Ol/YRudtYU1RWPPxATJEBMmQT6j14DlcnA+C2t4dBTsKyCo3CFSpNxYWsUXB4AUWFh8NTlFC8I5IKFigdEsTmKYAvSmHoW6LEa6ltcVT1cMKGod7leenEIVry6CPCfCZLmWDMuNviS8VfjkWG6auAGA17ryJxT36n/2b7knq4hWGhBne6F6UbYtYmU0fKKoQm3yItlwzF9GfDr5JFnvKXaM+2uUZiK+ccXZbdvMSzI05UTg/AT7yJUHuChxyCI2L+afsi5eFH8WcwVSy/z/pdEi4hxS8gwwIZGem6Oau6n2JbEy+8DhGLoIFoXAyO54UY63jhKxUGRQy7DNTqQFfZDBUIjZPyyoaNgHJVLqkuQs1uDbcbVM4k5f8Y6/NxjyRLYVbhl2lYK+sLxGTkv1jT5pmoMvgSjqhrPzuPdqqVU3CnejaJQDSrFzbGlW+d8GKzSsIkILAaSHJxcukgEB36al4lPMhEF4z4LEIYCA3YTHJS2AR3UWcKMF+asRffkwouXBfEc7c8TMbMSC26mA2qCyP8w3JiLs+upa8+AKlPVejmumqU7mKPbfF+4lvr8SXo4FPnQ4Xz8j/KWcHA4CT4mHWWW5sHjB2PuItRm5CtILGT6npxTkZW6vO1lhMG2Ecg93vHflc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: velero-credentials
      namespace: velero
    type: Opaque
